/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

/**
 *
 * @author Enzo Morales
 */
public class ventanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form ventanaMenu
     */
    public ventanaMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelFondoEnunciado = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(44, 185, 119));
        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(15, 123, 135));
        jLabelTitulo.setText("Registrar usuario");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(44, 185, 119));
        jLabelInstruccion1.setText("Bienvenido. Aquí puede agregar, eliminar o modificar un usua-");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(44, 185, 119));
        jLabelInstruccion2.setText("rio, para ello, por favor seleccione alguna opción.");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelFondoEnunciado.setBackground(new java.awt.Color(59, 83, 67));
        jLabelFondoEnunciado.setOpaque(true);
        getContentPane().add(jLabelFondoEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, 90));

        jButtonAgregar.setBackground(new java.awt.Color(59, 83, 67));
        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(44, 185, 119));
        jButtonAgregar.setText("Agregar usuario");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 140, 160, 30));

        jButtonEliminar.setBackground(new java.awt.Color(59, 83, 67));
        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(44, 185, 119));
        jButtonEliminar.setText("Eliminar usario");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 200, 160, 30));

        jButtonModificar.setBackground(new java.awt.Color(59, 83, 67));
        jButtonModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(44, 185, 119));
        jButtonModificar.setText("Modificar usuario");
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 260, 160, 30));

        jButtonSalir.setBackground(new java.awt.Color(59, 83, 67));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(15, 123, 135));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(130, 223, 92));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 123, 135), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        //new ventanaAgregarUsuario().setVisible(true);
        //dispose();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        //new ventanaEliminarUsuario().setVisible(true);
        //dispose();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoEnunciado;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
