/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Enzo Morales
 */
public class ventanaAgregarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ventanaAgregarUsuario
     */
    
    String nombre = null;
    String correoElectronico = null;
    String apellidos = null;
    Usuario usuario = null;
    
    public ventanaAgregarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelInstruccion1 = new javax.swing.JLabel();
        jLabelInstruccion2 = new javax.swing.JLabel();
        jLabelFondoEnunciado = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(54, 104, 167));
        jLabelTitulo.setText("Agregar usuario");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion1.setForeground(new java.awt.Color(189, 217, 241));
        jLabelInstruccion1.setText("Aquí puede agregar un usuario nuevo. Para ello, por favor in-");
        getContentPane().add(jLabelInstruccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelInstruccion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInstruccion2.setForeground(new java.awt.Color(189, 217, 241));
        jLabelInstruccion2.setText("grese los siguientes datos.");
        getContentPane().add(jLabelInstruccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabelFondoEnunciado.setBackground(new java.awt.Color(34, 65, 119));
        jLabelFondoEnunciado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondoEnunciado.setOpaque(true);
        getContentPane().add(jLabelFondoEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 90));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(54, 104, 167));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 123, -1, -1));

        jLabelApellidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelApellidos.setForeground(new java.awt.Color(54, 104, 167));
        jLabelApellidos.setText("Apellidos:");
        getContentPane().add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 173, -1, -1));

        jLabelCorreoElectronico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCorreoElectronico.setForeground(new java.awt.Color(54, 104, 167));
        jLabelCorreoElectronico.setText("Correo electrónico:");
        getContentPane().add(jLabelCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 223, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 120, 180, 30));

        jTextFieldApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 170, 180, 30));

        jTextFieldCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 220, 180, 30));

        jButtonAgregar.setBackground(new java.awt.Color(34, 65, 119));
        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(189, 217, 241));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(34, 65, 119));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(54, 104, 167));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabelFondo.setBackground(new java.awt.Color(131, 166, 204));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        new ventanaMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();
        String correoElectronico = jTextFieldCorreo.getText();
        String contrasenna = new Password(4, 8).getContraseña();
        Correo correoEnviar = new Correo();
        try {
            correoEnviar.enviarCorreo(correoElectronico, "asignación de contraseña", contrasenna);
        } catch (MessagingException ex) {
            Logger.getLogger(ventanaAgregarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (nombre.length() != 0 && apellidos.length() != 0 && correoElectronico.length() != 0) {
            ControlXml ctrl = new ControlXml();
            Usuario nuevoUsuario = new Usuario(nombre, apellidos, correoElectronico, contrasenna);
            this.usuario=nuevoUsuario;
            ctrl.addUsuario(nuevoUsuario);
            ctrl.save();
            
            JOptionPane.showMessageDialog(null, "El usuario ha sido agregado correctamente.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor asegúrese de llenar todos los campos de texto solicitados.", "Error: Campos vacíos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCorreoElectronico() {
        return correoElectronico;
    }

    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public JButton getjButtonAgregar() {
        return jButtonAgregar;
    }

    public void setjButtonAgregar(JButton jButtonAgregar) {
        this.jButtonAgregar = jButtonAgregar;
    }

    public JButton getjButtonVolver() {
        return jButtonVolver;
    }

    public void setjButtonVolver(JButton jButtonVolver) {
        this.jButtonVolver = jButtonVolver;
    }

    public JLabel getjLabelApellidos() {
        return jLabelApellidos;
    }

    public void setjLabelApellidos(JLabel jLabelApellidos) {
        this.jLabelApellidos = jLabelApellidos;
    }

    public JLabel getjLabelCorreoElectronico() {
        return jLabelCorreoElectronico;
    }

    public void setjLabelCorreoElectronico(JLabel jLabelCorreoElectronico) {
        this.jLabelCorreoElectronico = jLabelCorreoElectronico;
    }

    public JLabel getjLabelFondo() {
        return jLabelFondo;
    }

    public void setjLabelFondo(JLabel jLabelFondo) {
        this.jLabelFondo = jLabelFondo;
    }

    public JLabel getjLabelFondoEnunciado() {
        return jLabelFondoEnunciado;
    }

    public void setjLabelFondoEnunciado(JLabel jLabelFondoEnunciado) {
        this.jLabelFondoEnunciado = jLabelFondoEnunciado;
    }

    public JLabel getjLabelInstruccion1() {
        return jLabelInstruccion1;
    }

    public void setjLabelInstruccion1(JLabel jLabelInstruccion1) {
        this.jLabelInstruccion1 = jLabelInstruccion1;
    }

    public JLabel getjLabelInstruccion2() {
        return jLabelInstruccion2;
    }

    public void setjLabelInstruccion2(JLabel jLabelInstruccion2) {
        this.jLabelInstruccion2 = jLabelInstruccion2;
    }

    public JLabel getjLabelNombre() {
        return jLabelNombre;
    }

    public void setjLabelNombre(JLabel jLabelNombre) {
        this.jLabelNombre = jLabelNombre;
    }

    public JLabel getjLabelTitulo() {
        return jLabelTitulo;
    }

    public void setjLabelTitulo(JLabel jLabelTitulo) {
        this.jLabelTitulo = jLabelTitulo;
    }

    public JTextField getjTextFieldApellidos() {
        return jTextFieldApellidos;
    }

    public void setjTextFieldApellidos(JTextField jTextFieldApellidos) {
        this.jTextFieldApellidos = jTextFieldApellidos;
    }

    public JTextField getjTextFieldCorreo() {
        return jTextFieldCorreo;
    }

    public void setjTextFieldCorreo(JTextField jTextFieldCorreo) {
        this.jTextFieldCorreo = jTextFieldCorreo;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoEnunciado;
    private javax.swing.JLabel jLabelInstruccion1;
    private javax.swing.JLabel jLabelInstruccion2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
